### ISSUE TITLE
Please use modern cmake

### ISSUE THREAD

**Issue by Lectem** [xyproto/sdl2-examples#8]
It would be nice to use modern cmake and good practices.
Since newbies might begine from this repository, it should aim to do the right thing.

See also https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1 or https://github.com/Lectem/cpp-boilerplate  for more details and cmake good practices.

- Do not set `CMAKE_CXX_FLAGS` directly (https://github.com/xyproto/sdl2-examples/blob/master/c%2B%2B11-cmake/CMakeLists.txt#L9). For c++ standard requirements you can use `target_compile_features`
- Do not use `pkgconfig `when the official package already has a cmake config (https://github.com/xyproto/sdl2-examples/blob/master/c%2B%2B11-cmake/CMakeLists.txt#L12). Use `find_package` instead.
- Do not use `include_directories` (https://github.com/xyproto/sdl2-examples/blob/master/c%2B%2B11-cmake/CMakeLists.txt#L14). Use `target_include_directories` instead.

This could generally all be replaced with

```cmake
target_compile_features(${PROJECT_NAME} PRIVATE cxx_std_11)

find_package(SDL2 REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE SDL2::SDL2 SDL2::SDL2main)
```

**Comment by xyproto** [comment]
Thanks reporting, I'll look into modernizing the `CMakeLists.txt` files.

**Comment by xyproto** [comment]
Does `target_compile_features` work on all platforms now? The reason I used

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

was because

```cmake
add_compile_options(-std=c++11)
```

did not work on macOS at the time.

**Comment by xyproto** [comment]
The Travis CI test failed when using the CMake config files instead of `pkg-config`.

I've always found `pkg-config` to be a very reliable way to get compilation flags for a specific library. Is there any particular reason why CMake config files are considered to be better?

```
cd build && cmake -G Ninja -- ../c++17-cmake && ninja
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:6 (add_executable):
  Target "main" links to target "SDL2::SDL2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
CMake Error at CMakeLists.txt:6 (add_executable):
  Target "main" links to target "SDL2::SDL2main" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
-- Generating done
-- Build files have been written to: /home/travis/build/xyproto/sdl2-examples/build
The command "cd build && cmake -G Ninja -- ../c++17-cmake && ninja" exited with 1.
Done. Your build exited with 1.
```

Yes, GCC 5.4 indicates that the distro used on Travis CI is a bit old, but I think it's a valid goal to also want to support older distros, at least for C++14 and earlier.

**Comment by xyproto** [comment]
I ended up modernizing the CMake files a bit, but have the part that uses SDL2::SDL2 commented out, for now.

I especially appreciate the idea that as much as possible should be bound to the CMake targets.

Thanks.

**Comment by Lectem** [comment]
> ```cmake
> ```cmake
> add_compile_options(-std=c++11)
> ```
> 
> 
> did not work on macOS at the time.
> ```

Well it wouldn't work on windows either since -std=c++11 is only for GCC and Clang. On MacOS it might not have worked simply because the flag was not supported.

`target_compile_features` is the best way to set the standard, and `cxx_std_*` up to 17 has been available since CMake 3.8, so it should be safe to use. 




> I've always found `pkg-config` to be a very reliable way to get compilation flags for a specific library. Is there any particular reason why CMake config files are considered to be better?

The main reason is that it won't work on Windows, and if the SDL2 have any specific properties that are needed it will be automatically added when linking it (include directories, minimum standard, compile options), while with PKG config you only get the libs/ include dirs.




> 
> CMake Error at CMakeLists.txt:6 (add_executable):
>   Target "main" links to target "SDL2::SDL2" but the target was not found.
>   Perhaps a find_package() call is missing for an IMPORTED target, or an
>   ALIAS target is missing?

This is weird, `find_package` succeeded and the targets are not available ?
I downloaded ad85082 and was able to compile the `c++11-cmake` example just fine.
What OS was this run on ?

**Comment by Lectem** [comment]
Oh and I missed the `add_definitions`, it could also be replaced by `target_add_definitions`.
So
```cmake
target_compile_definitions(-DIMGDIR="../img/")
``` 

would become
```cmake
target_compile_definitions(-DIMGDIR="../img/")
```

**Comment by xyproto** [comment]
Thanks, I ended up with:

```cmake
target_compile_definitions(${PROJECT_NAME} PRIVATE IMGDIR="../img/")
```

Which seems to work nicely. :+1:
